#spring.application.name=demo-github
# Utilisation de variables d'environnement avec des valeurs par défaut
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:findb}
spring.datasource.username=${DB_USER:user_spring}
spring.datasource.password=${DB_PASS:password_spring}

# Configuration Hibernate pour la création automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
